# Generated by Django 4.2.7 on 2026-06-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_channel_tenant_department_tenant_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('head_of_department', 'Head of Department'), ('senior', 'Senior'), ('junior', 'Junior'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
    ]
