from django.urls import path
from .views import *
from .sso_views import sso_callback, sso_verify
from .license_webhook import license_provision, license_cancel, license_reactivate
urlpatterns = [
    path('auth/login/', login_view),
    path('auth/logout/', logout_view),
    path('auth/me/', profile_view),
    path('auth/change-password/', change_password_view),
    path('users/<int:id>/change-password/', admin_change_password),
    path('auth/csrf/', csrf_view),
    path('dashboard/', dashboard_view),
    path('notifications/', notifications_view),
    path('notifications/read-all/', notifications_read_all),
    path('notifications/<int:id>/read/', notification_read),
    path('approvals/', approvals_list),
    path('projects/', projects_list),
    path('projects/analytics/', project_analytics),
    path('projects/recycle-bin/', project_recycle_bin),
    path('projects/<int:id>/', project_detail),
    path('projects/<int:id>/kanban/', project_kanban),
    path('projects/<int:id>/restore/', project_restore),
    path('projects/<int:id>/purge/', project_purge),
    path('projects/<int:id>/submit-approval/', project_submit_approval),
    path('projects/<int:id>/approve/', project_approve),
    path('projects/<int:id>/reject/', project_reject),
    path('projects/<int:id>/members/', project_members),
    path('projects/<int:id>/members/<int:user_id>/', project_member_detail),
    path('tasks/', tasks_list),
    path('tasks/my/', my_tasks),
    path('tasks/department/', department_tasks),
    path('tasks/<int:id>/', task_detail),
    path('tasks/<int:id>/restore/', task_restore),
    path('tasks/<int:id>/purge/', task_purge),
    path('tasks/<int:id>/kanban/', task_kanban),
    path('tasks/<int:id>/subtasks/', task_subtasks),
    path('tasks/<int:id>/comments/', task_comments),
    path('tasks/<int:id>/attachments/', task_attachments),
    path('tasks/<int:id>/submit-approval/', task_submit_approval),
    path('tasks/<int:id>/approve/', task_approve),
    path('tasks/<int:id>/reject/', task_reject),
    path('subtasks/<int:id>/toggle/', subtask_toggle),
    path('subtasks/<int:id>/', subtask_delete),
    path('comments/<int:id>/', comment_delete),
    path('attachments/<int:id>/', attachment_delete),
    path('attachments/<int:id>/download/', attachment_download),
    path('users/workload/', users_workload),
    path('users/', users_list),
    path('users/<int:id>/', user_detail),
    path('users/<int:id>/toggle-active/', user_toggle_active),
    path('roles/', roles_list),
    path('roles/<int:id>/', role_detail),
    path('departments/', departments_list),
    path('departments/<int:id>/', department_detail),
    path('activity/', activity_view),
    path('messages/', messages_view),
    path('messages/dm/<int:user_id>/', dm_conversation),
    path('messages/channels/', channels_list),
    path('messages/channels/<int:channel_id>/', channel_detail),
    path('messages/dm/msg/<int:msg_id>/', dm_message_detail),
    path('messages/channels/msg/<int:msg_id>/', channel_message_detail),
    path('messages/channels/<int:channel_id>/members/', channel_members),
    path('messages/channels/<int:channel_id>/members/<int:user_id>/', channel_member_detail),
    # Extension requests
    path('extension-requests/', extension_requests_list),
    path('extension-requests/create/', extension_request_create),
    path('extension-requests/<int:id>/', extension_request_detail),
    path('extension-requests/<int:id>/approve/', extension_request_approve),
    path('extension-requests/<int:id>/reject/', extension_request_reject),
    # ── Jibble ──
    path('jibble/live/',       jibble_live_attendance),
    path('jibble/attendance/', jibble_attendance),
    path('jibble/employees/',  jibble_employees),
    path('jibble/timesheets/', jibble_timesheets),
    path('jibble/test/',       jibble_test),
    path('jibble/debug/',      debug_jibble),
    path('jibble/import-users/', jibble_import_users),
    
    path('sso/callback/', sso_callback),
    path('sso/verify/',   sso_verify),

    # ── License provisioning webhook (called by SaaS Platform) ──
    path('webhooks/license-provision/', license_provision),
    path('webhooks/license-cancel/', license_cancel),
    path('webhooks/license-reactivate/', license_reactivate),
]